### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by christophgapp** [gematik/Resource-Server-Example#1]
Der Server ist leider nicht wie beschrieben lauffähig. Können Sie die Doku noch dementsprechend anpassen?

**Comment by JuergenSchaefer** [comment]
Hallo,
vielen Dank für Deinen Hinweis. Es fehlt die Konfigurationsdatei, dies werden wir im nächsten Release korrigieren. 
Bitte erstelle Dir solange  manuell eine Konfigrautionsdatei ".env.dev" in dem root Verzeichnis.
Kopiere anschließend folgenden Inhalt in die Datei:

 #this is created for dev-environment. Here is up to you to modify it for your own locally use!
#-----------Ogr-IDP-------------
ISSUER=https://idp:8443/auth/realms/Testrealm
AUTHZ_PATH=https://idp:8443/auth/realms/Testrealm/protocol/openid-connect/auth
TOKEN_PATH=https://idp:8443/auth/realms/Testrealm/protocol/openid-connect/token
USER_INFO_PATH=https://idp:8443/auth/realms/Testrealm/protocol/openid-connect/userinfo
OGR_CLIENT_ID=oidc_rp_ogranwendung
#-----------Gem-CIDP-------------
CENTRAL_IDP_SERVER=http://localhost:8080
CENTRAL_IDP_SIGN_RESPONSE_ENDPOINT=http://localhost:8080/sign_response
CENTRAL_IDP_TOKEN_ENDPOINT=http://localhost:8080/token
CENTRAL_IDP_CLIENT_ID=AuthenticatorDevLocal
#-----------Rise-IDP (only remote) -------------
RISE_IDP_SERVER=https://IDP
RISE_IDP_SIGN_RESPONSE_ENDPOINT=https://AUTH_ENDPOINT/auth
RISE_IDP_TOKEN_ENDPOINT=https://TOKEN_ENDPOINT/token
RISE_IDP_CLIENT_ID=CLIENT_ID
RISE_REDIRECT_URI=https://REDIRECT_URI/callback
#-----------Relying Party Page-------------
CLIENT_HOST=http://localhost:8090
LOG_LEVEL=
#This is only for development purpose!!! Do not use in production
NODE_TLS_REJECT_UNAUTHORIZED=1


In diesem Beispiel wird für Dich nur der gem-cidp Abschnitt von Interesse sein. Dieser bezieht sich auf eine lokale Instanz des https://github.com/gematik/ref-idp-server.
