### ISSUE TITLE
Veraltete Dependencies

### ISSUE THREAD

**Issue by christophgapp** [gematik/Resource-Server-Example#2]
Hallo,

leider sind die Dependencies etwas veraltet, so wird zum Beispiel der oidc-provider von der aktuellen node.js Version (18) nicht unterstützt. 

...
oidc-provider WARNING: Unsupported Node.js runtime version. Use ^12.19.0, ^14.15.0, or ^16.13.0
...

**Comment by JuergenSchaefer** [comment]
Moin,
entschuldige die lange Reaktionszeit. Wir werden vorraussichtlich nächste Woche ein Release rausbringen mit aktualisierten dependencies . 
Langfristig werden wir dieses Projekt in https://github.com/gematik/Vue-Oidcauth-Sample überführen, da der Flow wie er zur Zeit implementiert ist, nicht korrekt ist.

**Comment by christophgapp** [comment]
Danke!
